### ISSUE TITLE
在运行deepsort_yolov4时候报错：str不需要被解码decode

### ISSUE THREAD

**Issue by kkhuangzekai** [yehengchen/Object-Detection-and-Tracking#109]
Traceback (most recent call last):
  File "/content/drive/My Drive/Object-Detection-and-Tracking-master/OneStage/yolo/deep_sort_yolov4/main.py", line 199, in <module>
    main(YOLO())
  File "/content/drive/My Drive/Object-Detection-and-Tracking-master/OneStage/yolo/deep_sort_yolov4/yolo.py", line 25, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/content/drive/My Drive/Object-Detection-and-Tracking-master/OneStage/yolo/deep_sort_yolov4/yolo.py", line 46, in generate
    self.yolo_model = load_model(model_path, custom_objects={'Mish': Mish}, compile=False)
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/saving.py", line 273, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

**Comment by yuxiaokui** [comment]
python版本太高了

**Comment by xuyao91** [comment]
the problem related with h5py. Downgrade your h5py.
pip install 'h5py==2.10.0' --force-reinstall
it works for me

**Comment by Apokar** [comment]
> 

works for me too ,thanks
