### ISSUE TITLE
convert yolov3.weights error

### ISSUE THREAD

**Issue by lmcrazy** [yehengchen/Object-Detection-and-Tracking#18]
hi,when i convert yolov3.weights to keras h5,the following error occurred.Please have a look. thanks!
---------
python convert.py yolov3.cfg yolov3.weights model_data/yolo6.h5
Using TensorFlow backend.
Loading weights.
Weights Header:  0 2 0 [32013312]
Parsing Darknet config.
aaa <_io.BytesIO object at 0x7f5a9a4f5308>
Traceback (most recent call last):
  File "convert.py", line 242, in <module>
    _main(parser.parse_args())
  File "convert.py", line 81, in _main
    cfg_parser.read_file(unique_config_file)
  File "/opt/anaconda3/lib/python3.7/configparser.py", line 717, in read_file
    self._read(f, source)
  File "/opt/anaconda3/lib/python3.7/configparser.py", line 1030, in _read
    if line.strip().startswith(prefix):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

**Comment by yehengchen** [comment]
@lmcrazy  Please check your config file.

**Comment by wdings** [comment]
您好，我在转换为Keras model时也出现上述的错误，请问怎么解决？

**Comment by yehengchen** [comment]
@wdings 可以试一下 [keras-yolo3](https://github.com/qqwweee/keras-yolo3)

**Comment by 6zc** [comment]
https://www.jianshu.com/u/d30115720666这个可以解决问题

**Comment by 6zc** [comment]
https://www.jianshu.com/u/d30115720666 这个可以解决问题
