### ISSUE TITLE
额，出现维度错误

### ISSUE THREAD

**Issue by fliessen** [yehengchen/Object-Detection-and-Tracking#26]
(temp) E:\BR\Object-Detection-and-Tracking-master\Object-Detection-and-Tracking-master\OneStage\yolo\deep_sort_yolov3> python main.py -c person -i .//test_video//testvideo1.mp4
Using TensorFlow backend.
d:\Anaconda3\envs\temp\lib\site-packages\sklearn\utils\linear_assignment_.py:21: DeprecationWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  DeprecationWarning)
2019-11-22 21:26:04.623552: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-11-22 21:26:04.844516: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1405] Found device 0 with properties:
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.44
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.59GiB
2019-11-22 21:26:04.851189: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1484] Adding visible gpu devices: 0
2019-11-22 21:26:05.547218: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-22 21:26:05.551120: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971]      0
2019-11-22 21:26:05.553729: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:984] 0:   N
2019-11-22 21:26:05.556927: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6340 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5)
./model_data/yolo-spp.h5 model, anchors, and classes loaded.
2019-11-22 21:26:13.711045: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1484] Adding visible gpu devices: 0
2019-11-22 21:26:13.714033: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-22 21:26:13.717546: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971]      0
2019-11-22 21:26:13.720182: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:984] 0:   N
2019-11-22 21:26:13.722600: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6340 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "d:\Anaconda3\envs\temp\lib\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "d:\Anaconda3\envs\temp\lib\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "d:\Anaconda3\envs\temp\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 43095 values, but the requested shape requires a multiple of 5577
         [[Node: Reshape_3 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv2d_60/BiasAdd, Reshape_3/shape)]]
         [[Node: concat_12/_2937 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3910_concat_12", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 182, in <module>
    main(YOLO())
  File "main.py", line 85, in main
    boxs,class_names = yolo.detect_image(image)
  File "E:\BR\Object-Detection-and-Tracking-master\Object-Detection-and-Tracking-master\OneStage\yolo\deep_sort_yolov3\yolo.py", line 118, in detect_image
    K.learning_phase(): 0
  File "d:\Anaconda3\envs\temp\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "d:\Anaconda3\envs\temp\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "d:\Anaconda3\envs\temp\lib\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "d:\Anaconda3\envs\temp\lib\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 43095 values, but the requested shape requires a multiple of 5577
         [[Node: Reshape_3 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv2d_60/BiasAdd, Reshape_3/shape)]]
         [[Node: concat_12/_2937 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3910_concat_12", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Reshape_3', defined at:
  File "main.py", line 182, in <module>
    main(YOLO())
  File "E:\BR\Object-Detection-and-Tracking-master\Object-Detection-and-Tracking-master\OneStage\yolo\deep_sort_yolov3\yolo.py", line 55, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "E:\BR\Object-Detection-and-Tracking-master\Object-Detection-and-Tracking-master\OneStage\yolo\deep_sort_yolov3\yolo.py", line 95, in generate
    score_threshold=self.score, iou_threshold=self.iou)
  File "E:\BR\Object-Detection-and-Tracking-master\Object-Detection-and-Tracking-master\OneStage\yolo\deep_sort_yolov3\yolo3\model.py", line 170, in yolo_eval
    anchors[anchor_mask[l]], num_classes, input_shape, image_shape)
  File "E:\BR\Object-Detection-and-Tracking-master\Object-Detection-and-Tracking-master\OneStage\yolo\deep_sort_yolov3\yolo3\model.py", line 148, in yolo_boxes_and_scores
    anchors, num_classes, input_shape)
  File "E:\BR\Object-Detection-and-Tracking-master\Object-Detection-and-Tracking-master\OneStage\yolo\deep_sort_yolov3\yolo3\model.py", line 105, in yolo_head
    feats, [-1, grid_shape[0], grid_shape[1], num_anchors, num_classes + 5])
  File "d:\Anaconda3\envs\temp\lib\site-packages\keras\backend\tensorflow_backend.py", line 1969, in reshape
    return tf.reshape(x, shape)
  File "d:\Anaconda3\envs\temp\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 7434, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "d:\Anaconda3\envs\temp\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "d:\Anaconda3\envs\temp\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "d:\Anaconda3\envs\temp\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "d:\Anaconda3\envs\temp\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 43095 values, but the requested shape requires a multiple of 5577
         [[Node: Reshape_3 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv2d_60/BiasAdd, Reshape_3/shape)]]
         [[Node: concat_12/_2937 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3910_concat_12", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

并未修改yolo.cfg中的参数

**Comment by fliessen** [comment]
额，一周前出的错误，一周后来发居然已经有人解决了……
