### ISSUE TITLE
NameError: global name 'yolo_eval' is not defined

### ISSUE THREAD

**Issue by 6zc** [yehengchen/Object-Detection-and-Tracking#37]
Traceback (most recent call last):
  File "main.py", line 172, in <module>
    main(YOLO())
  File "/home/xbot/Documents/Object-Detection-and-Tracking-master/OneStage/yolo/deep_sort_yolov3/yolo.py", line 51, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/home/xbot/Documents/Object-Detection-and-Tracking-master/OneStage/yolo/deep_sort_yolov3/yolo.py", line 89, in generate
    boxes, scores, classes = yolo_eval(self.yolo_model.output, self.anchors,
NameError: global name 'yolo_eval' is not defined

您好！我在使用deep_sort_yolov3，运行main时出现如上错误。咋办？

**Comment by 6zc** [comment]
It worked again:) nevermind
