### ISSUE TITLE
UnboundLocalError: local variable 'track' referenced before assignment

### ISSUE THREAD

**Issue by 6zc** [yehengchen/Object-Detection-and-Tracking#38]
Traceback (most recent call last):
  File "main.py", line 172, in <module>
    main(YOLO())
  File "main.py", line 158, in main
    if len(pts[track.track_id]) != None:
UnboundLocalError: local variable 'track' referenced before assignment

Why would this happened?
Using deep sort yolov3

**Comment by yehengchen** [comment]
@6zc Please check the path of the input video
